version: '3.1'
services:
  coffemachine-java: 
    image: coffemachine-backend
    build:
      context: coffemachine
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  coffemachine-angular: 
    image: coffemachine-angular
    build:
      context: coffemachine-angular
      dockerfile: Dockerfile
    ports:
      - 4200:80

